[General]
# seed-set = 0
# num-rngs = 1
cmdenv-express-mode = true
cmdenv-autoflush = true
*.roadsCanvasVisualizer.enabled = false
#It tells OMNeT++, "Do not print every single event. Calculate as fast as you humanly can in the background. 
#But every time 1 second of real-world time passes on my physical laptop clock, pause for a microsecond and 
#print whatever event you happen to be working on right now.
cmdenv-status-frequency = 1s

**.cmdenv-log-level = info

image-path = ../../images

network = RSUExampleScenario

##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = true

sim-time-limit = 1000s

**.scalar-recording = true
**.vector-recording = true

#*.playgroundSizeX = 2500m
#*.playgroundSizeY = 2500m
*.playgroundSizeX = 1000000m
*.playgroundSizeY = 1000000m
*.playgroundSizeZ = 50m


##########################################################
# Annotation parameters                                  #
##########################################################
*.annotations.draw = true

##########################################################
# Obstacle parameters                                    #
##########################################################
*.obstacles.obstacles = xmldoc("config.xml", "//AnalogueModel[@type='SimpleObstacleShadowing']/obstacles")

##########################################################
#            TraCIScenarioManager parameters             #
##########################################################
*.manager.updateInterval = 1s
*.manager.host = "localhost"
*.manager.port = 9999
*.manager.autoShutdown = true
*.manager.launchConfig = xmldoc("erlangen.launchd.xml")
*.manager.trafficLightModuleType = "org.car2x.veins.nodes.TrafficLight"

*.tls[*].mobility.x = 0
*.tls[*].mobility.y = 0
*.tls[*].mobility.z = 3

*.tls[*].applType = "org.car2x.veins.modules.application.traci.TraCIDemoTrafficLightApp"
*.tls[*].logicType ="org.car2x.veins.modules.world.traci.trafficLight.logics.TraCITrafficLightSimpleLogic"


##########################################################
#                       RSU SETTINGS                     #
#                                                        #
#                                                        #
##########################################################
*.rsu[0].mobility.x = 2000
*.rsu[0].mobility.y = 2000
*.rsu[0].mobility.z = 3

*.rsu[*].applType = "TraCIDemoRSU11p"
*.rsu[*].appl.headerLength = 80 bit
*.rsu[*].appl.sendBeacons = false
*.rsu[*].appl.dataOnSch = false
*.rsu[*].appl.beaconInterval = 1s
*.rsu[*].appl.beaconUserPriority = 7
*.rsu[*].appl.dataUserPriority = 5
*.rsu[*].nic.phy80211p.antennaOffsetZ = 0 m

##########################################################
#            11p specific parameters                     #
#                                                        #
#                    NIC-Settings                        #
##########################################################
*.connectionManager.sendDirect = true
*.connectionManager.maxInterfDist = 2600m
*.connectionManager.drawMaxIntfDist = false

*.**.nic.mac1609_4.useServiceChannel = false

*.**.nic.mac1609_4.txPower = 20mW
*.**.nic.mac1609_4.bitrate = 6Mbps
*.**.nic.phy80211p.minPowerLevel = -110dBm

*.**.nic.phy80211p.useNoiseFloor = true
*.**.nic.phy80211p.noiseFloor = -98dBm

*.**.nic.phy80211p.decider = xmldoc("config.xml")
*.**.nic.phy80211p.analogueModels = xmldoc("config.xml")
*.**.nic.phy80211p.usePropagationDelay = true

*.**.nic.phy80211p.antenna = xmldoc("antenna.xml", "/root/Antenna[@id='monopole']")
*.node[*].nic.phy80211p.antennaOffsetY = 0 m
*.node[*].nic.phy80211p.antennaOffsetZ = 1.895 m

##########################################################
#                      App Layer                         #
##########################################################
*.node[*].applType = "TraCIDemo11p"
*.node[*].appl.headerLength = 80 bit
*.node[*].appl.sendBeacons = false
*.node[*].appl.dataOnSch = false
*.node[*].appl.beaconInterval = 1s

##########################################################
#                      Mobility                          #
##########################################################
*.node[*].veinsmobility.x = 0
*.node[*].veinsmobility.y = 0
*.node[*].veinsmobility.z = 0
*.node[*].veinsmobility.setHostSpeed = false
*.node[0].veinsmobility.accidentCount = 0
#*.node[*0].veinsmobility.accidentStart = 73s
#*.node[*0].veinsmobility.accidentDuration = 50s
*.node[*].veinsmobility.accidentStart = 50s
*.node[*].veinsmobility.accidentDuration = 50s

[Config Default]

[Config WithBeaconing]
*.rsu[*].appl.sendBeacons = true
*.node[*].appl.sendBeacons = true

[Config WithChannelSwitching]
*.**.nic.mac1609_4.useServiceChannel = true
*.node[*].appl.dataOnSch = true
*.rsu[*].appl.dataOnSch = true

[Config Evaluation_Seeds]
description = "Runs 5 repetitions with different seeds (Beaconing ON)"
extends = WithBeaconing
# Run this configuration 5 times (Repetitions 0, 1, 2, 3, 4)
repeat = 5
# This automatically links the seed to the repetition number!
# Run 0 -> seed 0. Run 1 -> seed 1, etc.
seed-set = ${repetition}

[Config Throughput_Evaluation]
description = "Evaluates overall simulation throughput for different time limits"
repeat = 5
# This will automatically run 9 consecutive simulations!
sim-time-limit = ${sim_time=20, 100, 200, 400, 600, 800, 1000, 1200, 1500}s