// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sumo_cosimulation.proto
#ifndef GRPC_sumo_5fcosimulation_2eproto__INCLUDED
#define GRPC_sumo_5fcosimulation_2eproto__INCLUDED

#include "sumo_cosimulation.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace veinsthesis {

// The gRPC Service
class SumoCosimulation final {
 public:
  static constexpr char const* service_full_name() {
    return "veinsthesis.SumoCosimulation";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::veinsthesis::StepResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::veinsthesis::StepResponse>> AsyncExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::veinsthesis::StepResponse>>(AsyncExecuteStepRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::veinsthesis::StepResponse>> PrepareAsyncExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::veinsthesis::StepResponse>>(PrepareAsyncExecuteStepRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteStep(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::veinsthesis::StepResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ExecuteStep(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::veinsthesis::StepResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ExecuteStep(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::veinsthesis::StepResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::veinsthesis::StepResponse>* AsyncExecuteStepRaw(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::veinsthesis::StepResponse>* PrepareAsyncExecuteStepRaw(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::veinsthesis::StepResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::veinsthesis::StepResponse>> AsyncExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::veinsthesis::StepResponse>>(AsyncExecuteStepRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::veinsthesis::StepResponse>> PrepareAsyncExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::veinsthesis::StepResponse>>(PrepareAsyncExecuteStepRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response, std::function<void(::grpc::Status)>) override;
      void ExecuteStep(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::veinsthesis::StepResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ExecuteStep(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::veinsthesis::StepResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ExecuteStep(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::veinsthesis::StepResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::veinsthesis::StepResponse>* AsyncExecuteStepRaw(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::veinsthesis::StepResponse>* PrepareAsyncExecuteStepRaw(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteStep_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ExecuteStep(::grpc::ServerContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteStep() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExecuteStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteStep(::grpc::ServerContext* /*context*/, const ::veinsthesis::StepRequest* /*request*/, ::veinsthesis::StepResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteStep(::grpc::ServerContext* context, ::veinsthesis::StepRequest* request, ::grpc::ServerAsyncResponseWriter< ::veinsthesis::StepResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExecuteStep<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ExecuteStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ExecuteStep() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::veinsthesis::StepRequest, ::veinsthesis::StepResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response) { return this->ExecuteStep(context, request, response); }));}
    void SetMessageAllocatorFor_ExecuteStep(
        ::grpc::experimental::MessageAllocator< ::veinsthesis::StepRequest, ::veinsthesis::StepResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::veinsthesis::StepRequest, ::veinsthesis::StepResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ExecuteStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteStep(::grpc::ServerContext* /*context*/, const ::veinsthesis::StepRequest* /*request*/, ::veinsthesis::StepResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ExecuteStep(
      ::grpc::CallbackServerContext* /*context*/, const ::veinsthesis::StepRequest* /*request*/, ::veinsthesis::StepResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ExecuteStep(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::veinsthesis::StepRequest* /*request*/, ::veinsthesis::StepResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_ExecuteStep<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_ExecuteStep<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExecuteStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteStep() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExecuteStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteStep(::grpc::ServerContext* /*context*/, const ::veinsthesis::StepRequest* /*request*/, ::veinsthesis::StepResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteStep() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExecuteStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteStep(::grpc::ServerContext* /*context*/, const ::veinsthesis::StepRequest* /*request*/, ::veinsthesis::StepResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteStep(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ExecuteStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ExecuteStep() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExecuteStep(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ExecuteStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteStep(::grpc::ServerContext* /*context*/, const ::veinsthesis::StepRequest* /*request*/, ::veinsthesis::StepResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ExecuteStep(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ExecuteStep(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecuteStep : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecuteStep() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::veinsthesis::StepRequest, ::veinsthesis::StepResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::veinsthesis::StepRequest, ::veinsthesis::StepResponse>* streamer) {
                       return this->StreamedExecuteStep(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExecuteStep() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteStep(::grpc::ServerContext* /*context*/, const ::veinsthesis::StepRequest* /*request*/, ::veinsthesis::StepResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecuteStep(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::veinsthesis::StepRequest,::veinsthesis::StepResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ExecuteStep<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ExecuteStep<Service > StreamedService;
};

}  // namespace veinsthesis


#endif  // GRPC_sumo_5fcosimulation_2eproto__INCLUDED
