// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sumo_cosimulation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sumo_5fcosimulation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sumo_5fcosimulation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sumo_5fcosimulation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sumo_5fcosimulation_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sumo_5fcosimulation_2eproto;
namespace veinsthesis {
class StepRequest;
class StepRequestDefaultTypeInternal;
extern StepRequestDefaultTypeInternal _StepRequest_default_instance_;
class StepResponse;
class StepResponseDefaultTypeInternal;
extern StepResponseDefaultTypeInternal _StepResponse_default_instance_;
class VehicleState;
class VehicleStateDefaultTypeInternal;
extern VehicleStateDefaultTypeInternal _VehicleState_default_instance_;
}  // namespace veinsthesis
PROTOBUF_NAMESPACE_OPEN
template<> ::veinsthesis::StepRequest* Arena::CreateMaybeMessage<::veinsthesis::StepRequest>(Arena*);
template<> ::veinsthesis::StepResponse* Arena::CreateMaybeMessage<::veinsthesis::StepResponse>(Arena*);
template<> ::veinsthesis::VehicleState* Arena::CreateMaybeMessage<::veinsthesis::VehicleState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace veinsthesis {

// ===================================================================

class StepRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:veinsthesis.StepRequest) */ {
 public:
  inline StepRequest() : StepRequest(nullptr) {};
  virtual ~StepRequest();

  StepRequest(const StepRequest& from);
  StepRequest(StepRequest&& from) noexcept
    : StepRequest() {
    *this = ::std::move(from);
  }

  inline StepRequest& operator=(const StepRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StepRequest& operator=(StepRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StepRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StepRequest* internal_default_instance() {
    return reinterpret_cast<const StepRequest*>(
               &_StepRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StepRequest& a, StepRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StepRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StepRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StepRequest* New() const final {
    return CreateMaybeMessage<StepRequest>(nullptr);
  }

  StepRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StepRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StepRequest& from);
  void MergeFrom(const StepRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StepRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "veinsthesis.StepRequest";
  }
  protected:
  explicit StepRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sumo_5fcosimulation_2eproto);
    return ::descriptor_table_sumo_5fcosimulation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetTimeFieldNumber = 1,
  };
  // double target_time = 1;
  void clear_target_time();
  double target_time() const;
  void set_target_time(double value);
  private:
  double _internal_target_time() const;
  void _internal_set_target_time(double value);
  public:

  // @@protoc_insertion_point(class_scope:veinsthesis.StepRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double target_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sumo_5fcosimulation_2eproto;
};
// -------------------------------------------------------------------

class VehicleState PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:veinsthesis.VehicleState) */ {
 public:
  inline VehicleState() : VehicleState(nullptr) {};
  virtual ~VehicleState();

  VehicleState(const VehicleState& from);
  VehicleState(VehicleState&& from) noexcept
    : VehicleState() {
    *this = ::std::move(from);
  }

  inline VehicleState& operator=(const VehicleState& from) {
    CopyFrom(from);
    return *this;
  }
  inline VehicleState& operator=(VehicleState&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VehicleState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VehicleState* internal_default_instance() {
    return reinterpret_cast<const VehicleState*>(
               &_VehicleState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(VehicleState& a, VehicleState& b) {
    a.Swap(&b);
  }
  inline void Swap(VehicleState* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VehicleState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VehicleState* New() const final {
    return CreateMaybeMessage<VehicleState>(nullptr);
  }

  VehicleState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VehicleState>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VehicleState& from);
  void MergeFrom(const VehicleState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VehicleState* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "veinsthesis.VehicleState";
  }
  protected:
  explicit VehicleState(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sumo_5fcosimulation_2eproto);
    return ::descriptor_table_sumo_5fcosimulation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVehicleIdFieldNumber = 1,
    kRoadIdFieldNumber = 6,
    kPositionXFieldNumber = 2,
    kPositionYFieldNumber = 3,
    kSpeedFieldNumber = 4,
    kAngleFieldNumber = 5,
    kLengthFieldNumber = 7,
    kWidthFieldNumber = 8,
  };
  // string vehicle_id = 1;
  void clear_vehicle_id();
  const std::string& vehicle_id() const;
  void set_vehicle_id(const std::string& value);
  void set_vehicle_id(std::string&& value);
  void set_vehicle_id(const char* value);
  void set_vehicle_id(const char* value, size_t size);
  std::string* mutable_vehicle_id();
  std::string* release_vehicle_id();
  void set_allocated_vehicle_id(std::string* vehicle_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_vehicle_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_vehicle_id(
      std::string* vehicle_id);
  private:
  const std::string& _internal_vehicle_id() const;
  void _internal_set_vehicle_id(const std::string& value);
  std::string* _internal_mutable_vehicle_id();
  public:

  // string road_id = 6;
  void clear_road_id();
  const std::string& road_id() const;
  void set_road_id(const std::string& value);
  void set_road_id(std::string&& value);
  void set_road_id(const char* value);
  void set_road_id(const char* value, size_t size);
  std::string* mutable_road_id();
  std::string* release_road_id();
  void set_allocated_road_id(std::string* road_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_road_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_road_id(
      std::string* road_id);
  private:
  const std::string& _internal_road_id() const;
  void _internal_set_road_id(const std::string& value);
  std::string* _internal_mutable_road_id();
  public:

  // double position_x = 2;
  void clear_position_x();
  double position_x() const;
  void set_position_x(double value);
  private:
  double _internal_position_x() const;
  void _internal_set_position_x(double value);
  public:

  // double position_y = 3;
  void clear_position_y();
  double position_y() const;
  void set_position_y(double value);
  private:
  double _internal_position_y() const;
  void _internal_set_position_y(double value);
  public:

  // double speed = 4;
  void clear_speed();
  double speed() const;
  void set_speed(double value);
  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);
  public:

  // double angle = 5;
  void clear_angle();
  double angle() const;
  void set_angle(double value);
  private:
  double _internal_angle() const;
  void _internal_set_angle(double value);
  public:

  // double length = 7;
  void clear_length();
  double length() const;
  void set_length(double value);
  private:
  double _internal_length() const;
  void _internal_set_length(double value);
  public:

  // double width = 8;
  void clear_width();
  double width() const;
  void set_width(double value);
  private:
  double _internal_width() const;
  void _internal_set_width(double value);
  public:

  // @@protoc_insertion_point(class_scope:veinsthesis.VehicleState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vehicle_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr road_id_;
  double position_x_;
  double position_y_;
  double speed_;
  double angle_;
  double length_;
  double width_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sumo_5fcosimulation_2eproto;
};
// -------------------------------------------------------------------

class StepResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:veinsthesis.StepResponse) */ {
 public:
  inline StepResponse() : StepResponse(nullptr) {};
  virtual ~StepResponse();

  StepResponse(const StepResponse& from);
  StepResponse(StepResponse&& from) noexcept
    : StepResponse() {
    *this = ::std::move(from);
  }

  inline StepResponse& operator=(const StepResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StepResponse& operator=(StepResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StepResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StepResponse* internal_default_instance() {
    return reinterpret_cast<const StepResponse*>(
               &_StepResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StepResponse& a, StepResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(StepResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StepResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StepResponse* New() const final {
    return CreateMaybeMessage<StepResponse>(nullptr);
  }

  StepResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StepResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StepResponse& from);
  void MergeFrom(const StepResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StepResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "veinsthesis.StepResponse";
  }
  protected:
  explicit StepResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sumo_5fcosimulation_2eproto);
    return ::descriptor_table_sumo_5fcosimulation_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVehiclesFieldNumber = 1,
  };
  // repeated .veinsthesis.VehicleState vehicles = 1;
  int vehicles_size() const;
  private:
  int _internal_vehicles_size() const;
  public:
  void clear_vehicles();
  ::veinsthesis::VehicleState* mutable_vehicles(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::veinsthesis::VehicleState >*
      mutable_vehicles();
  private:
  const ::veinsthesis::VehicleState& _internal_vehicles(int index) const;
  ::veinsthesis::VehicleState* _internal_add_vehicles();
  public:
  const ::veinsthesis::VehicleState& vehicles(int index) const;
  ::veinsthesis::VehicleState* add_vehicles();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::veinsthesis::VehicleState >&
      vehicles() const;

  // @@protoc_insertion_point(class_scope:veinsthesis.StepResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::veinsthesis::VehicleState > vehicles_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sumo_5fcosimulation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StepRequest

// double target_time = 1;
inline void StepRequest::clear_target_time() {
  target_time_ = 0;
}
inline double StepRequest::_internal_target_time() const {
  return target_time_;
}
inline double StepRequest::target_time() const {
  // @@protoc_insertion_point(field_get:veinsthesis.StepRequest.target_time)
  return _internal_target_time();
}
inline void StepRequest::_internal_set_target_time(double value) {
  
  target_time_ = value;
}
inline void StepRequest::set_target_time(double value) {
  _internal_set_target_time(value);
  // @@protoc_insertion_point(field_set:veinsthesis.StepRequest.target_time)
}

// -------------------------------------------------------------------

// VehicleState

// string vehicle_id = 1;
inline void VehicleState::clear_vehicle_id() {
  vehicle_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& VehicleState::vehicle_id() const {
  // @@protoc_insertion_point(field_get:veinsthesis.VehicleState.vehicle_id)
  return _internal_vehicle_id();
}
inline void VehicleState::set_vehicle_id(const std::string& value) {
  _internal_set_vehicle_id(value);
  // @@protoc_insertion_point(field_set:veinsthesis.VehicleState.vehicle_id)
}
inline std::string* VehicleState::mutable_vehicle_id() {
  // @@protoc_insertion_point(field_mutable:veinsthesis.VehicleState.vehicle_id)
  return _internal_mutable_vehicle_id();
}
inline const std::string& VehicleState::_internal_vehicle_id() const {
  return vehicle_id_.Get();
}
inline void VehicleState::_internal_set_vehicle_id(const std::string& value) {
  
  vehicle_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void VehicleState::set_vehicle_id(std::string&& value) {
  
  vehicle_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:veinsthesis.VehicleState.vehicle_id)
}
inline void VehicleState::set_vehicle_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  vehicle_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:veinsthesis.VehicleState.vehicle_id)
}
inline void VehicleState::set_vehicle_id(const char* value,
    size_t size) {
  
  vehicle_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:veinsthesis.VehicleState.vehicle_id)
}
inline std::string* VehicleState::_internal_mutable_vehicle_id() {
  
  return vehicle_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* VehicleState::release_vehicle_id() {
  // @@protoc_insertion_point(field_release:veinsthesis.VehicleState.vehicle_id)
  return vehicle_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VehicleState::set_allocated_vehicle_id(std::string* vehicle_id) {
  if (vehicle_id != nullptr) {
    
  } else {
    
  }
  vehicle_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), vehicle_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:veinsthesis.VehicleState.vehicle_id)
}
inline std::string* VehicleState::unsafe_arena_release_vehicle_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:veinsthesis.VehicleState.vehicle_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return vehicle_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void VehicleState::unsafe_arena_set_allocated_vehicle_id(
    std::string* vehicle_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (vehicle_id != nullptr) {
    
  } else {
    
  }
  vehicle_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      vehicle_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:veinsthesis.VehicleState.vehicle_id)
}

// double position_x = 2;
inline void VehicleState::clear_position_x() {
  position_x_ = 0;
}
inline double VehicleState::_internal_position_x() const {
  return position_x_;
}
inline double VehicleState::position_x() const {
  // @@protoc_insertion_point(field_get:veinsthesis.VehicleState.position_x)
  return _internal_position_x();
}
inline void VehicleState::_internal_set_position_x(double value) {
  
  position_x_ = value;
}
inline void VehicleState::set_position_x(double value) {
  _internal_set_position_x(value);
  // @@protoc_insertion_point(field_set:veinsthesis.VehicleState.position_x)
}

// double position_y = 3;
inline void VehicleState::clear_position_y() {
  position_y_ = 0;
}
inline double VehicleState::_internal_position_y() const {
  return position_y_;
}
inline double VehicleState::position_y() const {
  // @@protoc_insertion_point(field_get:veinsthesis.VehicleState.position_y)
  return _internal_position_y();
}
inline void VehicleState::_internal_set_position_y(double value) {
  
  position_y_ = value;
}
inline void VehicleState::set_position_y(double value) {
  _internal_set_position_y(value);
  // @@protoc_insertion_point(field_set:veinsthesis.VehicleState.position_y)
}

// double speed = 4;
inline void VehicleState::clear_speed() {
  speed_ = 0;
}
inline double VehicleState::_internal_speed() const {
  return speed_;
}
inline double VehicleState::speed() const {
  // @@protoc_insertion_point(field_get:veinsthesis.VehicleState.speed)
  return _internal_speed();
}
inline void VehicleState::_internal_set_speed(double value) {
  
  speed_ = value;
}
inline void VehicleState::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:veinsthesis.VehicleState.speed)
}

// double angle = 5;
inline void VehicleState::clear_angle() {
  angle_ = 0;
}
inline double VehicleState::_internal_angle() const {
  return angle_;
}
inline double VehicleState::angle() const {
  // @@protoc_insertion_point(field_get:veinsthesis.VehicleState.angle)
  return _internal_angle();
}
inline void VehicleState::_internal_set_angle(double value) {
  
  angle_ = value;
}
inline void VehicleState::set_angle(double value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:veinsthesis.VehicleState.angle)
}

// string road_id = 6;
inline void VehicleState::clear_road_id() {
  road_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& VehicleState::road_id() const {
  // @@protoc_insertion_point(field_get:veinsthesis.VehicleState.road_id)
  return _internal_road_id();
}
inline void VehicleState::set_road_id(const std::string& value) {
  _internal_set_road_id(value);
  // @@protoc_insertion_point(field_set:veinsthesis.VehicleState.road_id)
}
inline std::string* VehicleState::mutable_road_id() {
  // @@protoc_insertion_point(field_mutable:veinsthesis.VehicleState.road_id)
  return _internal_mutable_road_id();
}
inline const std::string& VehicleState::_internal_road_id() const {
  return road_id_.Get();
}
inline void VehicleState::_internal_set_road_id(const std::string& value) {
  
  road_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void VehicleState::set_road_id(std::string&& value) {
  
  road_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:veinsthesis.VehicleState.road_id)
}
inline void VehicleState::set_road_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  road_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:veinsthesis.VehicleState.road_id)
}
inline void VehicleState::set_road_id(const char* value,
    size_t size) {
  
  road_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:veinsthesis.VehicleState.road_id)
}
inline std::string* VehicleState::_internal_mutable_road_id() {
  
  return road_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* VehicleState::release_road_id() {
  // @@protoc_insertion_point(field_release:veinsthesis.VehicleState.road_id)
  return road_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VehicleState::set_allocated_road_id(std::string* road_id) {
  if (road_id != nullptr) {
    
  } else {
    
  }
  road_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), road_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:veinsthesis.VehicleState.road_id)
}
inline std::string* VehicleState::unsafe_arena_release_road_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:veinsthesis.VehicleState.road_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return road_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void VehicleState::unsafe_arena_set_allocated_road_id(
    std::string* road_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (road_id != nullptr) {
    
  } else {
    
  }
  road_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      road_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:veinsthesis.VehicleState.road_id)
}

// double length = 7;
inline void VehicleState::clear_length() {
  length_ = 0;
}
inline double VehicleState::_internal_length() const {
  return length_;
}
inline double VehicleState::length() const {
  // @@protoc_insertion_point(field_get:veinsthesis.VehicleState.length)
  return _internal_length();
}
inline void VehicleState::_internal_set_length(double value) {
  
  length_ = value;
}
inline void VehicleState::set_length(double value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:veinsthesis.VehicleState.length)
}

// double width = 8;
inline void VehicleState::clear_width() {
  width_ = 0;
}
inline double VehicleState::_internal_width() const {
  return width_;
}
inline double VehicleState::width() const {
  // @@protoc_insertion_point(field_get:veinsthesis.VehicleState.width)
  return _internal_width();
}
inline void VehicleState::_internal_set_width(double value) {
  
  width_ = value;
}
inline void VehicleState::set_width(double value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:veinsthesis.VehicleState.width)
}

// -------------------------------------------------------------------

// StepResponse

// repeated .veinsthesis.VehicleState vehicles = 1;
inline int StepResponse::_internal_vehicles_size() const {
  return vehicles_.size();
}
inline int StepResponse::vehicles_size() const {
  return _internal_vehicles_size();
}
inline void StepResponse::clear_vehicles() {
  vehicles_.Clear();
}
inline ::veinsthesis::VehicleState* StepResponse::mutable_vehicles(int index) {
  // @@protoc_insertion_point(field_mutable:veinsthesis.StepResponse.vehicles)
  return vehicles_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::veinsthesis::VehicleState >*
StepResponse::mutable_vehicles() {
  // @@protoc_insertion_point(field_mutable_list:veinsthesis.StepResponse.vehicles)
  return &vehicles_;
}
inline const ::veinsthesis::VehicleState& StepResponse::_internal_vehicles(int index) const {
  return vehicles_.Get(index);
}
inline const ::veinsthesis::VehicleState& StepResponse::vehicles(int index) const {
  // @@protoc_insertion_point(field_get:veinsthesis.StepResponse.vehicles)
  return _internal_vehicles(index);
}
inline ::veinsthesis::VehicleState* StepResponse::_internal_add_vehicles() {
  return vehicles_.Add();
}
inline ::veinsthesis::VehicleState* StepResponse::add_vehicles() {
  // @@protoc_insertion_point(field_add:veinsthesis.StepResponse.vehicles)
  return _internal_add_vehicles();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::veinsthesis::VehicleState >&
StepResponse::vehicles() const {
  // @@protoc_insertion_point(field_list:veinsthesis.StepResponse.vehicles)
  return vehicles_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace veinsthesis

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sumo_5fcosimulation_2eproto
