// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sumo_cosimulation.proto

#include "sumo_cosimulation.pb.h"
#include "sumo_cosimulation.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace veinsthesis {

static const char* SumoCosimulation_method_names[] = {
  "/veinsthesis.SumoCosimulation/ExecuteStep",
};

std::unique_ptr< SumoCosimulation::Stub> SumoCosimulation::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SumoCosimulation::Stub> stub(new SumoCosimulation::Stub(channel));
  return stub;
}

SumoCosimulation::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ExecuteStep_(SumoCosimulation_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SumoCosimulation::Stub::ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::veinsthesis::StepResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ExecuteStep_, context, request, response);
}

void SumoCosimulation::Stub::experimental_async::ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ExecuteStep_, context, request, response, std::move(f));
}

void SumoCosimulation::Stub::experimental_async::ExecuteStep(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::veinsthesis::StepResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ExecuteStep_, context, request, response, std::move(f));
}

void SumoCosimulation::Stub::experimental_async::ExecuteStep(::grpc::ClientContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ExecuteStep_, context, request, response, reactor);
}

void SumoCosimulation::Stub::experimental_async::ExecuteStep(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::veinsthesis::StepResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ExecuteStep_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::veinsthesis::StepResponse>* SumoCosimulation::Stub::AsyncExecuteStepRaw(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::veinsthesis::StepResponse>::Create(channel_.get(), cq, rpcmethod_ExecuteStep_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::veinsthesis::StepResponse>* SumoCosimulation::Stub::PrepareAsyncExecuteStepRaw(::grpc::ClientContext* context, const ::veinsthesis::StepRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::veinsthesis::StepResponse>::Create(channel_.get(), cq, rpcmethod_ExecuteStep_, context, request, false);
}

SumoCosimulation::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SumoCosimulation_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SumoCosimulation::Service, ::veinsthesis::StepRequest, ::veinsthesis::StepResponse>(
          [](SumoCosimulation::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::veinsthesis::StepRequest* req,
             ::veinsthesis::StepResponse* resp) {
               return service->ExecuteStep(ctx, req, resp);
             }, this)));
}

SumoCosimulation::Service::~Service() {
}

::grpc::Status SumoCosimulation::Service::ExecuteStep(::grpc::ServerContext* context, const ::veinsthesis::StepRequest* request, ::veinsthesis::StepResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace veinsthesis

